# Generated by Django 3.0.7 on 2020-06-19 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('ticker', models.CharField(max_length=10, unique=True, verbose_name='Ticker')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Current Value')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Average Price')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('type_order', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1, verbose_name='Type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Value')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Stock')),
            ],
        ),
    ]
