# Generated by Django 3.0.7 on 2020-06-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
    ]
