# Generated by Django 3.0.7 on 2020-07-01 17:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200621_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[core.validators.tax_validator], verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=13, validators=[core.validators.value_validator], verbose_name='Value'),
        ),
    ]
