# Generated by Django 3.0.7 on 2020-07-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200701_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='average_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Average Price'),
        ),
    ]
