# Generated by Django 3.0.7 on 2020-07-02 13:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200701_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[core.validators.value_validator], verbose_name='Total Value'),
        ),
    ]
