# Generated by Django 3.0.7 on 2020-07-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200702_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stock'),
        ),
    ]
