# Generated by Django 3.0.7 on 2020-07-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200707_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_update',
            field=models.DateField(blank=True, null=True, verbose_name='Last price update'),
        ),
    ]
