# Generated by Django 3.0.7 on 2020-07-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stock_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last price update'),
        ),
    ]
